version: '3.7'
services:
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local
    ports:
      - 5432:5432
    networks:
      - k8s-mozart409

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - k8s-mozart409

volumes:
  data:
networks:
  k8s-mozart409:
    driver: bridge
